import Head from 'next/head'
import Homepage from '../src/components/Home/Homepage'
import Script from 'next/script';
/* import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] }) */

export default function Home () {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />

        <link rel='icon' href='/favicon.ico' />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1, shrink-to-fit=no'
        />

      </Head>
      <Homepage />
      <Script
        src="/js/owl.carousel.min.js"
        strategy="lazyOnload"
        onLoad={() =>
          console.log(`script loaded correctly, window.FB has been populated`)
        }
      />
    </>
  )
}
